### ISSUE TITLE
timer / alarm option 

### ISSUE THREAD

**Issue by bonanza123** [stefaro/harbour-waterfish#1]
Thanks for.this nice app. Would it be possible to add a timer /reminder functionality? For example it would be useful to have an alarm if I haven't added some drink to log in the last X hours.

**Comment by stefaro** [comment]
Thank you for the suggestion. It is a good idea to have a reminder functionality in the app. I'll implement it once i have time... It could take few months, since I have a lot of other things at hand currently.

**Comment by stefaro** [comment]
This has been implemented now.. App is also submitted to Harbour QA. Hopefully it'll be accepted.

**Comment by stefaro** [comment]
App has been approved by QA. You can updated it on your phone now.
