### ISSUE TITLE
nice statistics

### ISSUE THREAD

**Issue by bonanza123** [stefaro/harbour-waterfish#2]
It would be perfect if it would be possible to gather statistics for each day (meaning automatic reset every day and daily / weekly / monthly data) in a graphical way.

**Comment by stefaro** [comment]
Thanks for the suggestion again :)
I was actually thinking this also. I'll implement it at some point.

**Comment by stefaro** [comment]
I have created a statistics view in the app now. Stats are stored in sqlite db. I submitted app to QA now, let's see if they accept it :)

**Comment by stefaro** [comment]
App was approved, you can update now.

**Comment by bonanza123** [comment]
thank you very much!
